import type { RegistryEntry } from "../../../shared.ts";

export const postman_agentProvider: RegistryEntry = {
  id: "postman-agent",
  alias: "postman",
  format: "openai",
  executor: "postman-agent",
  baseUrl: "https://identity.getpostman.com",
  authType: "apikey",
  authHeader: "cookie",
  defaultContextLength: 200000,
  models: [
    {
      id: "claude-opus-4-8",
      name: "Claude Opus 4.8",
      supportsReasoning: true,
      supportsVision: true,
      contextLength: 200000,
      maxOutputTokens: 128000,
    },
    {
      id: "claude-sonnet-4-6",
      name: "Claude Sonnet 4.6",
      supportsReasoning: true,
      supportsVision: true,
      contextLength: 200000,
      maxOutputTokens: 64000,
    },
    {
      id: "gpt-5.5",
      name: "GPT-5.5",
      supportsReasoning: true,
      supportsVision: true,
      contextLength: 1050000,
      maxOutputTokens: 128000,
    },
    {
      id: "gpt-5.5-xhigh",
      name: "GPT-5.5 (xHigh)",
      supportsReasoning: true,
      supportsVision: true,
      contextLength: 1050000,
      maxOutputTokens: 128000,
    },
    {
      id: "gpt-5.5-high",
      name: "GPT-5.5 (High)",
      supportsReasoning: true,
      supportsVision: true,
      contextLength: 1050000,
      maxOutputTokens: 128000,
    },
    {
      id: "gpt-5.5-medium",
      name: "GPT-5.5 (Medium)",
      supportsReasoning: true,
      supportsVision: true,
      contextLength: 1050000,
      maxOutputTokens: 128000,
    },
    {
      id: "gpt-5.5-low",
      name: "GPT-5.5 (Low)",
      supportsReasoning: true,
      supportsVision: true,
      contextLength: 1050000,
      maxOutputTokens: 128000,
    },
    {
      id: "gpt-5.6-sol",
      name: "GPT-5.6 Sol",
      supportsReasoning: true,
      supportsVision: true,
      contextLength: 1050000,
      maxOutputTokens: 128000,
    },
    {
      id: "gpt-5.6-sol-xhigh",
      name: "GPT-5.6 Sol (xHigh)",
      supportsReasoning: true,
      supportsVision: true,
      contextLength: 1050000,
      maxOutputTokens: 128000,
    },
    {
      id: "gpt-5.6-terra",
      name: "GPT-5.6 Terra",
      supportsReasoning: true,
      supportsVision: true,
      contextLength: 1050000,
      maxOutputTokens: 128000,
    },
    {
      id: "gpt-5.6-terra-xhigh",
      name: "GPT-5.6 Terra (xHigh)",
      supportsReasoning: true,
      supportsVision: true,
      contextLength: 1050000,
      maxOutputTokens: 128000,
    },
    {
      id: "gpt-5.6-luna",
      name: "GPT-5.6 Luna",
      supportsReasoning: true,
      supportsVision: true,
      contextLength: 1050000,
      maxOutputTokens: 128000,
    },
    {
      id: "gpt-5.6-luna-xhigh",
      name: "GPT-5.6 Luna (xHigh)",
      supportsReasoning: true,
      supportsVision: true,
      contextLength: 1050000,
      maxOutputTokens: 128000,
    },
    {
      id: "gpt-5.4",
      name: "GPT-5.4",
      supportsReasoning: true,
      supportsVision: true,
      contextLength: 1050000,
      maxOutputTokens: 128000,
    },
    {
      id: "gpt-5.4-xhigh",
      name: "GPT-5.4 (xHigh)",
      supportsReasoning: true,
      supportsVision: true,
      contextLength: 1050000,
      maxOutputTokens: 128000,
    },
    {
      id: "thinking",
      name: "Thinking (Extended)",
      supportsReasoning: true,
      contextLength: 200000,
      maxOutputTokens: 64000,
    },
    {
      id: "auto",
      name: "Auto (Optimized)",
      contextLength: 200000,
      maxOutputTokens: 64000,
    },
  ],
};
